In [1]:
import numpy as np

In [5]:
# From List
print("1D Array")
print(np.array([1,2,3,4,5])) # 1D
print("-----------------------")
print("2D Array")
print(np.array([[1,2,3],[4,5,6]])) # 2D

1D Array
[1 2 3 4 5]
-----------------------
2D Array
[[1 2 3]
 [4 5 6]]


In [10]:
# From Scratch
print("zeros")
print(np.zeros((3,3)))
print("-----------------------")
print("ones")
print(np.ones((3,3)))
print("-----------------------")
print("full")
print(np.full((2,3),20))
print("-----------------------")
print("eye")
print(np.eye(4))
print("-----------------------")
print("arange")
print(np.arange(1,11))
print(np.arange(1,11,5))
print("-----------------------")
print("linspace")
print(np.linspace(0,1,5))
print("-----------------------")

zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----------------------
ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----------------------
full
[[20 20 20]
 [20 20 20]]
-----------------------
eye
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----------------------
arange
[ 1  2  3  4  5  6  7  8  9 10]
[1 6]
-----------------------
linspace
[0.   0.25 0.5  0.75 1.  ]
-----------------------


In [12]:
# Checking array Properties
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print("-----------------------")
print("Shape: ",arr.shape)
print("Size: ",arr.size)
print("Dimensions: ",arr.ndim)
print("Data type: ",arr.dtype)

[[1 2 3 4]
 [4 5 6 7]]
-----------------------
Shape:  (2, 4)
Size:  8
Dimensions:  2
Data type:  int64


In [17]:
# Changing DataTypes
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)
print(arr)

arr_int = arr.astype(np.int64)
print(arr_int)

float64
[1. 2. 3.]
[1 2 3]


In [19]:
# Reshaping and Flattening array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print("-------------------------------")
reshaped = arr.reshape((3, 2))
print(reshaped)
print("-------------------------------")
flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)

(2, 3)
-------------------------------
[[1 2]
 [3 4]
 [5 6]]
-------------------------------
[1 2 3 4 5 6]
