In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])

In [2]:
# indexing
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
# slicing
print(arr[0:4])
print(arr[::2])
print(arr[::-1])

[10 20 30 40]
[10 30]
[40 30 20 10]


### ** Slicing returns a view, not a copy! Changes affect the original array.**
#### Why?
- Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
- Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [4]:
arr = np.array([1,3,5,7,9,11,13,15])
print("Before Slicing: ",arr)
sliced = arr[1:6]
sliced[0] = 888
print("Slicing part: ",sliced)
print("After Slicing: ",arr)

Before Slicing:  [ 1  3  5  7  9 11 13 15]
Slicing part:  [888   5   7   9  11]
After Slicing:  [  1 888   5   7   9  11  13  15]


In [5]:
sliced = sliced[1:6].copy()
sliced[0] = 999
print("Sliced part return copy not original: ",sliced)
print("Original not changed because of copy funtion: ",arr)

Sliced part return copy not original:  [999   7   9  11]
Original not changed because of copy funtion:  [  1 888   5   7   9  11  13  15]


### Fancy Indexing
- Return the selected indices
- arr[index1, undex2,..]

In [6]:
arr = np.array([20,30,40,50,60,70,80])
index = [1,3,5]
print(arr[index])

[30 50 70]


### Boolean Masking
- This is a powerful way to filter large datasets efficiently!

In [7]:
arr = np.array([10,4,27,2,8,19,11,3,22,1])
print(arr>20)
print(arr[arr>20])

[False False  True False False False False False  True False]
[27 22]


### Practice Problems
- Create a 3×3 array filled with random numbers and print its shape.
- Convert an array of floats [1.1, 2.2, 3.3] into integers.
- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
- Reshape a 1D array of size 9 into a 3×3 matrix.
- Use boolean masking to filter numbers greater than 50 in an array.

In [8]:
arr = np.arange(1,10)
reshaped = arr.reshape((3,3))
print(reshaped)
print("Size:",reshaped.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Size: (3, 3)


In [9]:
arr = np.array([1.1, 2.2, 3.3], dtype = np.int64)
print(arr)

[1 2 3]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
idx = [1,3,5]
print(arr[idx])

[2 4 6]


In [11]:
arr = np.arange(1,10)
reshaped = arr.reshape((3,3))
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[arr>50])

[ 60  70  80  90 100]
